--------------------------------------------------------
-- Archivo creado  - miércoles-diciembre-07-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table AFICIONADOS_PELIGROSOS
--------------------------------------------------------

  CREATE TABLE "HR"."AFICIONADOS_PELIGROSOS" 
   (	"AFICIONADOS_P_ID" NUMBER, 
	"DNI_AFICIONADO_P" VARCHAR2(20 BYTE), 
	"FECHA_AFICIONADO_P" DATE, 
	"NOMBRE_AFICIONADO_P" VARCHAR2(50 BYTE), 
	"AFICION_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "HR"."AFICIONADOS_PELIGROSOS"."AFICIONADOS_P_ID" IS 'ID DE LOS AFICIONAOS PELIGROSO';
   COMMENT ON COLUMN "HR"."AFICIONADOS_PELIGROSOS"."DNI_AFICIONADO_P" IS 'DNI AFICIONADO PELIGROSO';
   COMMENT ON COLUMN "HR"."AFICIONADOS_PELIGROSOS"."FECHA_AFICIONADO_P" IS 'FECHA DE NACIMIENTO AFICIONADO PELIGROSO';
   COMMENT ON COLUMN "HR"."AFICIONADOS_PELIGROSOS"."NOMBRE_AFICIONADO_P" IS 'NOMBRE DEL AFICIONADO PELIGROSO';
   COMMENT ON COLUMN "HR"."AFICIONADOS_PELIGROSOS"."AFICION_ID" IS 'ID DE LA AFICION';
REM INSERTING into HR.AFICIONADOS_PELIGROSOS
SET DEFINE OFF;
Insert into HR.AFICIONADOS_PELIGROSOS (AFICIONADOS_P_ID,DNI_AFICIONADO_P,FECHA_AFICIONADO_P,NOMBRE_AFICIONADO_P,AFICION_ID) values ('1','12345678a',to_date('01/01/85','DD/MM/RR'),'Mariano Rajoy','1');
Insert into HR.AFICIONADOS_PELIGROSOS (AFICIONADOS_P_ID,DNI_AFICIONADO_P,FECHA_AFICIONADO_P,NOMBRE_AFICIONADO_P,AFICION_ID) values ('2','12345678b',to_date('01/01/86','DD/MM/RR'),'Pedro Sanchez','1');
Insert into HR.AFICIONADOS_PELIGROSOS (AFICIONADOS_P_ID,DNI_AFICIONADO_P,FECHA_AFICIONADO_P,NOMBRE_AFICIONADO_P,AFICION_ID) values ('3','12345678c',to_date('01/01/87','DD/MM/RR'),'Albert Rivera','1');
Insert into HR.AFICIONADOS_PELIGROSOS (AFICIONADOS_P_ID,DNI_AFICIONADO_P,FECHA_AFICIONADO_P,NOMBRE_AFICIONADO_P,AFICION_ID) values ('4','12345678d',to_date('01/01/88','DD/MM/RR'),'Pablo Iglesias','1');
--------------------------------------------------------
--  DDL for Index AFICIONADOS_PELIGROSOS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."AFICIONADOS_PELIGROSOS_PK" ON "HR"."AFICIONADOS_PELIGROSOS" ("AFICIONADOS_P_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table AFICIONADOS_PELIGROSOS
--------------------------------------------------------

  ALTER TABLE "HR"."AFICIONADOS_PELIGROSOS" ADD CONSTRAINT "AFICIONADOS_PELIGROSOS_PK" PRIMARY KEY ("AFICIONADOS_P_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HR"."AFICIONADOS_PELIGROSOS" MODIFY ("AFICIONADOS_P_ID" NOT NULL ENABLE);
